#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER db WITH PASSWORD 'db';

	-- DROP DATABASE IF EXISTS db;

	CREATE DATABASE db
		WITH
		OWNER = db
		ENCODING = 'UTF8';

	GRANT ALL ON DATABASE db TO db;
EOSQL
