#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER db WITH PASSWORD 'db';
	CREATE DATABASE db WITH OWNER db;
	GRANT ALL PRIVILEGES ON DATABASE db TO db;
EOSQL
