#!/bin/bash

set -o errexit
set -o pipefail


if [ "$FLASK_ENV" == "production" ]; then
        gunicorn wsgi:app --bind 0.0.0.0:8080 --workers 2 --log-file -
else
        flask run --host=0.0.0.0 --port=8080
fi
